project_name: uddns

before:
  hooks:
    - go mod tidy

builds:
  -
    id: default
    binary: uddns
    flags: [-trimpath]
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_386
      - linux_amd64
      - linux_amd64_v3
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_arm64
      - linux_mips_softfloat
      - linux_mips_hardfloat
      - linux_mipsle_softfloat
      - linux_mipsle_hardfloat
      - linux_mips64
      - linux_mips64le
      - linux_s390x
      - linux_riscv64
      - freebsd_amd64
      - windows_386
      - windows_amd64
      - windows_arm64
checksum:
  name_template: 'checksums.txt'

archives:
  - id: default
    builds:
      - default
    builds_info:
      mode: 0755
    format: zip
    format_overrides:
      - goos: linux
        format: tar.gz

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
